actor_rollout_ref:
  actor:
    checkpoint:
      async_save: false
      load_contents: null
      save_contents:
      - model
      - optimizer
      - extra
    clip_ratio: 0.2
    clip_ratio_c: 3.0
    clip_ratio_high: 0.2
    clip_ratio_low: 0.2
    entropy_coef: 0.0
    fsdp:
      entropy_checkpointing: false
      entropy_from_logits_with_chunking: false
      forward_only: false
      fsdp1_forward_prefetch: false
      fsdp1_use_orig_params: false
      fsdp2_offload_policy: false
      fsdp2_reshard_after_forward: true
      fsdp_size: null
      fsdp_version: 2
      model_dtype: float32
      optimizer_offload: false
      param_offload: false
      ulysses_sequence_parallel_size: 1
      use_torch_compile: true
      wrap_min_num_params: 0
    kl_loss_coef: 0.001
    kl_loss_type: kl
    loss_agg_mode: token-mean
    optim:
      betas:
      - 0.9
      - 0.999
      clip_grad: null
      lr: 1.0e-05
      lr_warmup_steps_ratio: 0.0
      min_lr_ratio: 0.0
      num_cycles: 0.5
      warmup_style: constant
      weight_decay: 0.01
    policy_loss:
      clip_cov_lb: 1.0
      clip_cov_ratio: 0.0002
      clip_cov_ub: 1.0
      kl_cov_ratio: 0.0002
      loss_mode: vanilla
      ppo_kl_coef: 0.1
    ppo_epochs: 1
    ppo_max_token_len_per_gpu: 16384
    ppo_mini_batch_size: 256
    profiler:
      all_ranks: false
      enable: false
      npu_analysis: true
      npu_contents: []
      npu_discrete: true
      npu_level: null
      nsys_discrete: true
      ranks: []
      save_path: null
      tool: null
      torch_memory_stack_depth: 32
      torch_memory_trace_alloc_max_entries: 1000000
      torch_step_end: null
      torch_step_start: 0
    shufle: false
    tis_imp_ratio_cap: -1.0
    use_dynamic_bsz: false
    use_fused_kernels: true
    use_kl_loss: false
    use_torch_compile: true
  hybrid_engine: true
  model:
    path: meta-llama/Llama-3.1-8B-Instruct
    use_shm: false
  nccl_timeout: 600
  rollout:
    do_sample: true
    dtype: bfloat16
    enable_async: false
    enable_chunked_prefill: true
    enable_prefix_caching: true
    enforce_eager: false
    free_cache_engine: true
    gpu_memory_utilization: 0.5
    ignore_eos: false
    layered_summon: false
    load_format: hf
    max_model_len: null
    max_num_batched_tokens: 8192
    max_num_seqs: 1024
    n: 1
    name: meta-llama/Llama-3.1-8B-Instruct
    over_sample_rate: 0.0
    profiler:
      all_ranks: false
      enable: false
      npu_analysis: true
      npu_contents: []
      npu_discrete: true
      npu_level: null
      nsys_discrete: true
      ranks: []
      save_path: null
      tool: null
      torch_memory_stack_depth: 32
      torch_memory_trace_alloc_max_entries: 1000000
      torch_step_end: null
      torch_step_start: 0
    prompt_length: 1024
    response_length: 2048
    sglang_kwargs: {}
    sglang_multi_stage_wake_up: false
    temperature: 1.0
    tensor_model_parallel_size: 2
    top_k: null
    top_p: 1.0
    update_weights_bucket_megabytes: 512
    vllm_cudagraph_capture_sizes: null
    vllm_kwargs: {}
algorithm:
  adv_estimator: gae
  gamma: 1.0
  grpo_norm_adv_by_std: false
  kl_ctrl_adaptive: false
  kl_ctrl_coef: 0.001
  kl_penalty: kl
  lam: 1.0
  use_kl_in_reward: false
critic:
  checkpoint:
    async_save: false
    load_contents: null
    save_contents:
    - model
    - optimizer
    - extra
  cliprange_value: 0.5
  enable: false
  forward_max_token_len_per_gpu: 16384
  loss_agg_mode: token-mean
  model:
    path: ???
    use_shm: false
  optim:
    betas:
    - 0.9
    - 0.999
    clip_grad: null
    lr: 1.0e-05
    lr_warmup_steps_ratio: 0.0
    min_lr_ratio: 0.0
    num_cycles: 0.5
    warmup_style: constant
    weight_decay: 0.01
  ppo_epochs: 1
  ppo_max_token_len_per_gpu: 16384
  ppo_mini_batch_size: 256
  profiler:
    all_ranks: false
    enable: false
    npu_analysis: true
    npu_contents: []
    npu_discrete: true
    npu_level: null
    nsys_discrete: true
    ranks: []
    save_path: null
    tool: null
    torch_memory_stack_depth: 32
    torch_memory_trace_alloc_max_entries: 1000000
    torch_step_end: null
    torch_step_start: 0
  rollout_n: null
  shuffle: false
  use_dynamic_bsz: false
data:
  dataloader_num_workers: 1
  filter_overlong_prompts: false
  image_key: images
  max_prompt_length: 512
  max_response_length: 1024
  prompt_key: prompt
  reward_fn_key: data_source
  shuffle: true
  tokenizer: null
  train_batch_size: 8
  train_files:
  - ./mock_dataset/mock_dataset.parquet
  truncation: error
  use_shm: false
  val_batch_size: 8
  val_files:
  - ./mock_dataset/mock_dataset.parquet
  validation_shuffle: false
  video_key: videos
global_profiler:
  all_ranks: false
  enable: false
  npu_analysis: true
  npu_contents: []
  npu_discrete: true
  npu_level: null
  nsys_discrete: true
  ranks: []
  save_path: null
  tool: null
  torch_memory_stack_depth: 32
  torch_memory_trace_alloc_max_entries: 1000000
  torch_step_end: null
  torch_step_start: 0
ray:
  dashboard: localhost:8265
  num_cpus: null
trainer:
  balance_batch: true
  critic_warmup: 0
  default_hdfs_dir: null
  default_local_dir: checkpoints/verl
  del_local_ckpt_after_load: false
  device: cuda
  esi_redundant_time: 0
  experiment_name: debug
  log_val_generations: 0
  logger:
  - console
  - wandb
  max_actor_ckpt_to_keep: null
  max_critic_ckpt_to_keep: null
  n_gpus_per_node: 1
  n_nodes: 1
  project_name: verl_project
  ray_wait_register_center_timeout: 300
  resume_from_path: null
  resume_mode: auto
  rollout_data_dir: null
  save_freq: -1
  test_freq: -1
  total_epochs: 30
  total_training_steps: null
  use_legacy_worker_impl: false
  val_before_train: true
  val_only: false
  validation_data_dir: null
