name: "Sphinx: Render docs"

on:
  push:
    branches:
      - docs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install deps
        run: |
          sudo apt update -y 
          sudo apt install -y graphviz 
          python3 -m pip install sphinx-tabs
          python3 -m pip install shibuya

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build API
        run: |
          sphinx-apidoc -o docs/source/ref src/multimeditron

      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'

